version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql